FROM node:lts-buster as builder
WORKDIR /mern-stack/client
COPY ./client ./
RUN npm ci
ARG facebook_app_id
ENV REACT_APP_FACEBOOK_APP_ID=${facebook_app_id}
ARG google_client_id
ENV REACT_APP_GOOGLE_CLIENT_ID=${google_client_id}
RUN npm run build

FROM nginx:stable-alpine
ARG port
EXPOSE ${port}
COPY ./client/nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /wib/client/build /usr/share/nginx/html